### ISSUE TITLE
Style not applied to UITabBarItem

### ISSUE THREAD

**Issue by ghost** [werediver/StyleSheet#1]
Hello,
I tried to apply a Style to UITabBarItem, but the Style-block is never called. (All other Styles are working)

`Style<FooterFontStyle, UITabBarItem> {
          $0.setTitleTextAttributes([NSFontAttributeName: FontSmall], for: .normal)
}`
`extension UITabBarItem: FooterFontStyle { }`

Can you tell me, if I'm making something wrong, or fix this problem?
I could not figure out, why StyleSheet is not working for UITabBarItems.

Regards and Thanks

**Comment by werediver** [comment]
Hello.
StyleSheet is pretty close to `UIAppearance` under the hood. It means that StyleSheet needs a safe and universal method to inject its handler into a styled class. This is possible for `UIView` subclasses because of their known life-cycle, but not for any arbitrary class.

Notice that `UITabBarItem` inherits from `UIBarItem` and `NSObject`, but not from `UIView`, therefore you cannot directly apply neither StyleSheet nor `UIAppearance` to `UITabBarItem` or its subclasses.

You need to find a way to operate on `UIView` subclasses to achieve the desired look & feel.
Hope this help.

**Comment by ghost** [comment]
Hello,
Thank you for your quick response.
You are completely right.
I will use UIAppearance.

Thanks and regards

**Comment by werediver** [comment]
I've thought over your question a bit more, and it seems my answer wasn't comprehensive.

**First**, `UIBarItem` conforms to `UIAppearance` protocol, and it means that `UIAppearance` _can_ be applied to `UIBarItem` and its subclasses. It also means that StyleSheet can also be applied to them, just use `RootStyle.autoapply(style: appStyle, mode: .Appearance)` when setting up StyleSheet in your app.

StyleSheet supports two modes for installing its handler into UIKit. One is direct method-swizzling and the other is "hitchhiking" `UIAppearance`. The latter means that StyleSheet will work everywhere where `UIAppearance` does.

It seems that `.Appearance` mode should be the default one.

**Second**, it's possible to support styling for `UIViewController` and its subclasses, if it really makes sense.

I would appreciate you (and anyone interested) for providing additional feedback taking into account the above.

**Comment by werediver** [comment]
One more update.

StyleSheet v2.1.0 can't work with `UIBarItem` and its subclasses as is, though it's easy to cover this hierarchy. In theory. In practice, I can't manage to kickstart `UIAppearance` for `UIBarButtonItem` on an iOS 10 Simulator at all. Looks like Apple wrecked `UIAppearance` support in `UIBarItem` and/or `UIBarButtonItem` at some point. ~Can anyone check it, please?~

Anyway, `UIViewController` styling support is still possible, if considered useful (so your feedback is welcome!).

**Comment by werediver** [comment]
I've discovered very surprising behavior of `UIBarButtonItem` with relation to `UIAppearance` styling. It seems not possible to apply a style to an instance of `UIBarButtonItem`, and it's necessary to subclass first and apply a style directly to a subclass, otherwise the style is just ignored. Moreover, even after subclassing it's not possible to call a custom setter added in the subclass through its appearance-proxy.

In the absence of an adequate workaround, I would prefer not to deal with this mess. There is `RootStyle.apply(to:)` for manual style application and possibly a support for `UIViewController` styling.

Any thoughts?

**Comment by werediver** [comment]
And it's impossible to override a method in a `UIBarButtonItem` subclass. But it's not a class-cluster. Very dark voodoo there.

**Comment by ghost** [comment]
Hello.
First of all, I think .Swizzle should be the default one, because UIAppearance is very limited. And .Swizzle work like a charm (except in special cases like this one :)).

Second:
Currently I'm not able to apply a Style with .Appearance (The Block is not called) to a subclass of UITabBarItem.
`try RootStyle.autoapply(style: StyleSheet(styles: [
            Style<FooterFontStyle, TestBarItem> {
                $0.setTitleTextAttributes([NSFontAttributeName: FontMedium17], for: .normal)
            }
            ]), mode: .Appearance)`
`class TestBarItem: UITabBarItem, FooterFontStyle { }`

**Comment by werediver** [comment]
Okay, here is the final conclusion.

`UIBarItem`, `UIBarButtonItem` and their subclasses doesn't have a view-like life-cycle, therefore StyleSheet can't hook up to them as it does with `UIView` subclasses using direct swizzling.

It's also not possible to hitchhike `UIAppearance` with these classes, because their appearance-proxy doesn't seems to forward invocations as expected (it possibly changes the target).

It doesn't seem possible to amend the behavior of the standard appearance-proxy (without dirty hacks) as well.

It also doesn't seem to be a good idea to monkey-patch all the (known) `UIBarItem`/`UIBarButtonItem` consumers to apply appearance.

So I see no appropriate way to solve the issue at the moment. Will document it in the `README.md`.
